services:
  spring-deploy-student2-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKERHUB_USERNAME}/spring-deploy-student2-app:latest
    container_name: spring-deploy-student2-app
    ports:
      - ${APP_PORT:-9002}:${APP_PORT:-9002}
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --quiet --tries=1 --spider http://localhost:$${APP_PORT:-9002}/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - classroom_classroom_net


networks:
  classroom_classroom_net:
    external: true
